export const API_KEY = '5VCS4PSBY8UPQTU3';
export const APIS = {
    BSE_STOCK_DAILY_FULL: 'https://www.alphavantage.co/query?function=' + 
    'TIME_SERIES_DAILY&outputsize=full'
}
export const STOCKS = ['ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BHARTIARTL','DRREDDY','HCLTECH','HDFC','HDFCBANK','HINDUNILVR','ICICIBANK','INDUSINDBK','INFY','ITC','KOTAKBANK','LT','M&M','MARUTI','NESTLEIND','NTPC','ONGC','POWERGRID','RELIANCE','SBIN','SUNPHARMA','TCS','TECHM','TITAN','ULTRACEMCO'];